- ros_topic_name: /joint_states
  gz_topic_name: /world/underwater/model/atr_mp_rov/joint_state
  ros_type_name: sensor_msgs/msg/JointState
  gz_type_name: ignition.msgs.Model
  direction: GZ_TO_ROS

- ros_topic_name: /atr_mp_rov/thrusters/t1/force
  gz_topic_name: atr_mp_rov/thrusters/t1/force
  ros_type_name: std_msgs/msg/Float64
  gz_type_name: ignition.msgs.Double
  direction: ROS_TO_GZ

- ros_topic_name: /atr_mp_rov/thrusters/t2/force
  gz_topic_name: atr_mp_rov/thrusters/t2/force
  ros_type_name: std_msgs/msg/Float64
  gz_type_name: ignition.msgs.Double
  direction: ROS_TO_GZ

- ros_topic_name: /atr_mp_rov/thrusters/t3/force
  gz_topic_name: atr_mp_rov/thrusters/t3/force
  ros_type_name: std_msgs/msg/Float64
  gz_type_name: ignition.msgs.Double
  direction: ROS_TO_GZ

- ros_topic_name: /atr_mp_rov/thrusters/t4/force
  gz_topic_name: atr_mp_rov/thrusters/t4/force
  ros_type_name: std_msgs/msg/Float64
  gz_type_name: ignition.msgs.Double
  direction: ROS_TO_GZ

- ros_topic_name: /atr_mp_rov/thrusters/t5/force
  gz_topic_name: atr_mp_rov/thrusters/t5/force
  ros_type_name: std_msgs/msg/Float64
  gz_type_name: ignition.msgs.Double
  direction: ROS_TO_GZ

- ros_topic_name: /atr_mp_rov/thrusters/t6/force
  gz_topic_name: atr_mp_rov/thrusters/t6/force
  ros_type_name: std_msgs/msg/Float64
  gz_type_name: ignition.msgs.Double
  direction: ROS_TO_GZ

- ros_topic_name: /atr_mp_rov/thrusters/t7/force
  gz_topic_name: atr_mp_rov/thrusters/t7/force
  ros_type_name: std_msgs/msg/Float64
  gz_type_name: ignition.msgs.Double
  direction: ROS_TO_GZ

- ros_topic_name: /atr_mp_rov/thrusters/t8/force
  gz_topic_name: atr_mp_rov/thrusters/t8/force
  ros_type_name: std_msgs/msg/Float64
  gz_type_name: ignition.msgs.Double
  direction: ROS_TO_GZ

- ros_topic_name: /tf
  gz_topic_name: /model/atr_mp_rov/pose
  ros_type_name: tf2_msgs/msg/TFMessage
  gz_type_name: ignition.msgs.Pose_V
  direction: GZ_TO_ROS

- ros_topic_name: /nav/ins_odom
  gz_topic_name: /nav/ins_odom
  ros_type_name: nav_msgs/msg/Odometry
  gz_type_name: ignition.msgs.Odometry
  direction: GZ_TO_ROS

- ros_topic_name: /ins/imu
  gz_topic_name: /world/underwater/model/atr_mp_rov/link/base_link/sensor/ins_imu/imu
  ros_type_name: sensor_msgs/msg/Imu
  gz_type_name: ignition.msgs.IMU
  direction: GZ_TO_ROS

- ros_topic_name: /clock
  gz_topic_name: /clock
  ros_type_name: rosgraph_msgs/msg/Clock
  gz_type_name: ignition.msgs.Clock
  direction: GZ_TO_ROS